### ISSUE TITLE
error linux en raspberry pi

### ISSUE THREAD

**Issue by rriosalido** [vadimkantorov/wemosetup#5]
$ python3 wemosetup.py discover

  File "wemosetup.py", line 200
    ['''<DeviceStatus><IsGroupAction>NO</IsGroupAction><DeviceID available="YES">{}</DeviceID><CapabilityID>{}</CapabilityID><CapabilityValue>{}</CapabilityValue></DeviceStatus>'''.format(bulb_device_id, 10006, new_binary_state) for bulb_device_id in bulbs.keys()]
       ^
SyntaxError: invalid syntax

**Comment by vadimkantorov** [comment]
Please send a PR if you end up fixing it!

**Comment by vadimkantorov** [comment]
It was originally in Python2, then I ported it to Python3 but haven't tested it

**Comment by rriosalido** [comment]
Really I tried to fix, but I don't know how.

for bulb_device_id in bulbs.keys()]
                              ^
